### ISSUE TITLE
More info on how this was connected

### ISSUE THREAD

**Issue by lemiesz** [phord/Jarvis#1]
Hi, 

Forgive me I am not vert experience with IoT controllers. Could you possible give me some more detail on how you connected the wifi module to your desk, if you still have it could I see a picture?  

Also, do you think it would be possible for me to prototype something like this with a direct ethernet connection from my laptop.

**Comment by malfroid** [comment]
I am also very much interested on how to practically connect a [V3 Nodemcu-CH340 board](https://nl.aliexpress.com/item/32665100123.html?spm=a2g0s.9042311.0.0.40694c4d0S8hyg) (based on ESP8266 ES-12E) through 8P8C connector and UTP cable to the Fully Jarvis components (desk handset, desk controller box).

Do you strip the different wires in an UTP cable and solder to the ESP8266 pins?

How do you connect three UTP cables coming from desk handset, the desk controller box and the new components (ESP8266)? Do you use some kind of Ethernet hub for this?

**Comment by phord** [comment]
At first I used some stripped spare CAT-5 cable to make it easier to reverse-engineer the signal pins from the Jarvis controller.  I brought these out onto an 8-pin connector on a breadboard and attached my logic analyzer to do signal captures.  I use the [USB Logic Analyzer](https://www.sparkfun.com/products/15033) from Sparkfun with [sigrok/PulseView](https://learn.sparkfun.com/tutorials/using-the-usb-logic-analyzer-with-sigrok-pulseview) on Linux.

After that, I connected an ESP8266 to the same breadboard and started tinkering from there.  It was rather ugly.

I started to design a proper circuit in some EDA tool, but I'm terrible at that. So I took the quick route one afternoon and drew some traces in an online [Pebble](http://pebble.my-board.org/P_for_FF.html) tool.  I'd post the netlist here, but it's not terribly useful unless you have the same board I do.  Also, I'm not sure it's correct; I only used it as a guide.  I ended up moving things further apart later and I left off the boot-mode switches.
![image](https://user-images.githubusercontent.com/123908/101545973-eb286680-395c-11eb-8c4f-6971fceb2885.png)

Columns 1-8:  RJ-45 connectors
Columns 10-15: FTDI serial programming interface
Columns 20-28: Digistump Oak ESP-8266 daughterboard

I didn't use a NodeMCU module for this, but I easily could.  I used an ESP8266-based Digistump Oak board because I have a few handy from their kickstarter a few years ago. I don't recommend them, otherwise, since their plans got shanghaied by a poorly executed partnership with Particle.io.

I breadboarded it on my bench to get it working.  Later I converted that to the Pebble breadboard layout above just so I could double-check things and play with other ideas.

The interface is really simple.  I draw power from the Jarvis controller itself.  There is almost always enough current to drive the ESP8266.  I have had some occasional problems that might be caused by brownouts, but I'm still not sure.  

The only clever part worth mentioning is that I mounted two RJ-45 jacks on the board in a pass-thru configuration.  That is, there are two RJ-45's mounted together, one is rotated 180 degrees on two axes, so the pins all connect "straight through".  This is easier to see on the next picture.
* Conn1.Pin1 goes to Conn2.Pin1
* Conn1.Pin2 goes to Conn2.Pin2
* ...
* Conn1.Pin8 goes to Conn2.Pin8

Look at the pair of connectors at H1-8 and I1-8 on the Pebble breadboard above.  One of those is actually below the board pointing down instead of up.  Each pair of pins on those two connectors is electrically connected (because of the breadboard). Then I mounted one RJ-45 to the top set of pins and the other one to the bottom set of pins.  The bottom connector is rotated and turned around to face the opposite direction so the pins all connect as described.

![PXL_20201207_180654016](https://user-images.githubusercontent.com/123908/101544048-ed3cf600-3959-11eb-9eac-73781495f85a.jpg)

Then I plug the Jarvis Handset's RJ-45 cable into one of these (it doesn't matter which one), and I use a regular 8-pin network patch cable to connect the module to the Jarvis controller itself.  

By the way, the handset is optional.  You could drive it all from the ESP8266.  The passthrough works well, though.

Note: If you get the [RJ-45 breakout board from SparkFun](https://www.sparkfun.com/products/716), it makes it easy to stack these on headers.  But be careful when assembling it because Pin-8 is mis-labeled as Pin1 and vice-versa.  Read the user comments on the product page to see more details.

**Comment by phord** [comment]
Here's another view of the board in the same orientation as the Pebble image. 
![image](https://user-images.githubusercontent.com/123908/101547427-13b16000-395f-11eb-8462-85f6e11bdaa4.png)
![image](https://user-images.githubusercontent.com/123908/101545973-eb286680-395c-11eb-8c4f-6971fceb2885.png)
I found I needed more space for the FTDI connector to fit because the FTDI-board is wider than the connector.  So I moved the Oak pins over two more places and removed the switches.  I think I had the serial Tx/Rx pins reversed on the Oak, too.  Even though you can't see it here, the green and blue wires that go to pins 24/25 are backwards.

**Comment by phord** [comment]
> Also, do you think it would be possible for me to prototype something like this with a direct ethernet connection from my laptop.
@lemiesz The RJ-45 connector here is not used as an Ethernet connection.  The electrical signals are all different.  So no, you cannot connect this to your laptop's Ethernet port.
